name: image_cropper_for_web
description: A Flutter plugin for Web supports cropping images
repository: https://github.com/hnvn/flutter_image_cropper
version: 2.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  image_cropper_platform_interface: #^4.0.0
    git:
      url: https://github.com/UrosTodosijevic/cropper_libraries.git
      path: image_cropper_platform_interface-4.0.0

  js: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperPlugin
        fileName: image_cropper_for_web.dart
